# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200, verbose_name='Betreff')),
                ('body', models.TextField(max_length=4, verbose_name='Meldung')),
                ('test_email', models.EmailField(blank=True, max_length=254, verbose_name='Test-Empfänger')),
                ('was_sended', models.BooleanField(default=False, editable=False, verbose_name='Versand gestartet')),
                ('total_sended', models.IntegerField(editable=False, null=True, verbose_name='Anzahl Empfänger')),
                ('recipients', models.TextField(blank=True, editable=False, verbose_name='Empfänger')),
                ('date_sended', models.DateTimeField(editable=False, null=True, verbose_name='Versanddatum')),
                ('recipient_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Versender Liste')),
            ],
            options={
                'verbose_name': 'Meldung',
                'verbose_name_plural': 'Meldungen',
            },
        ),
    ]
